pref_label: "Status"
description: ""
members:
  - pref_label: "Invalid"
    description: "Record is missing some critical fields (such as from an unclean import from a foreign system) and should be reviewed and corrected or replaced before being used by any application."
  - pref_label: "Deleted"
    description: "Record has been deleted by an application. Use this status instead of deleting records from a table, unless these records are duplicated or corrupted. Some application admins may be able to 'undelete' records. Deleted records can only be viewed by admins. The only modification possible is to their status."
  - pref_label: "Disabled"
    description: "Record is valid but not viewable by end users. Other records relating to this one should not display references to it to non-admin users. In some cases (such as item belonging to a category with 'disabled' status) the application can decide not to show the related records either. New relations cannot be created."
  - pref_label: "Active"
    description: "Record is available for use."
  - pref_label: "Archived"
    description: "Record is available for view and discovery. No modifications can be made to it, except to its status by the owner or admins. Special access controls (e.g. hide from public users) and/or functionality (such as a special storage location) can be attached to this status."
