pref_label: "View Type"
description: "Viewing angle, overall or detail, etc."
type: "AICType.ViewTypeList"
additional_types: []
item_type: "AICType.ViewType"
additional_item_types: ["AICType.Authority"]
uid: "LS-6"
members:
  - pref_label: "Back/Verso"
    description: ""
    uid: "VW-1"
  - pref_label: "Front/Recto"
    description: ""
    uid: "VW-2"
  - pref_label: "Annotated Condition Diagram"
    description: ""
    uid: "VW-3"
  - pref_label: "Overall"
    description: ""
    uid: "VW-5"
  - pref_label: "Detail/Macro"
    description: ""
    uid: "VW-6"
  - pref_label: "Proper Right"
    description: ""
    uid: "VW-8"
  - pref_label: "Proper Left"
    description: ""
    uid: "VW-10"
  - pref_label: "Top"
    description: ""
    uid: "VW-11"
  - pref_label: "Bottom"
    description: ""
    uid: "VW-12"
  - pref_label: "Location map (for macro, micro and samples)"
    description: ""
    uid: "VW-13"
  - pref_label: "Photomicrograph"
    description: ""
    uid: "VW-14"
