development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8984/solr/aic_development" %>
test: &test
  adapter: solr
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8985}/solr/aic_test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>

